### ISSUE TITLE
"Zip entry 'MANIFEST/MANIFEST.MF' tries to escape target directory" when decompiling 22w42a Minecraft client jar

### ISSUE THREAD

**Issue by 0x3C50** [FabricMC/intellij-fernflower#20]
https://github.com/FabricMC/intellij-fernflower/blob/49f5561beca2d4efbf94762452858f032841b31e/src/org/jetbrains/java/decompiler/struct/StructContext.java#L143 seems to be the issue

Exception:
```
Exception in thread "main" java.lang.RuntimeException: Zip entry 'META-INF/MANIFEST.MF' tries to escape target directory
	at org.jetbrains.java.decompiler.struct.StructContext.addArchive(StructContext.java:143)
	at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:86)
	at org.jetbrains.java.decompiler.struct.StructContext.addSpace(StructContext.java:64)
	at org.jetbrains.java.decompiler.main.Fernflower.addSource(Fernflower.java:73)
	at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.addSource(ConsoleDecompiler.java:112)
	at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.main(ConsoleDecompiler.java:80)
```

Cmd line: `java -jar fernflower/build/libs/fernflower.jar -dgs=true jars/mc.jar decomp`

This also results in the same error: `cd decomp; java -jar ../fernflower/build/libs/fernflower.jar -dgs=true ../jars/mc.jar .`

Happens on fresh build with latest commit. No other logs other than the exception are visible.

**Comment by Veeloxfire** [comment]
If you're looking for a fix: Using an absolute path for the jar rather than a relative path fixed this for me. But its still not ideal

**Comment by 0x3C50** [comment]
> If you're looking for a fix: Using an absolute path for the jar rather than a relative path fixed this for me. But its still not ideal

I've tried that too, didn't work either

**Comment by W01fh4cker** [comment]
> 

thx u very much :)
